<!DOCTYPE html>
<html lang="en">
  <head>
    <?php echo $this->headTitle('Simple Chat') ?>
    <?php echo $this->headMeta()
        ->setCharset('utf-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('description', '')
        ->appendName('author', '');
        //->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    ?>

    <!-- Bootstrap -->
    <?php echo $this->headLink(array(
                                    'rel' => 'shortcut icon',
                                    'type' => 'image/vnd.microsoft.icon',
                                    'href' => $this->basePath('favicon.ico')
                                    )
                                )
					->prependStylesheet($this->basePath('css/style.css'))
					->prependStylesheet($this->basePath('css/parsley.css'))
                    ->prependStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.min.css'));
    ?>

    <?php echo $this->headScript(); ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
	</head>
	<body>
	<div id="wrapper">
		<?php echo $this->content; ?>
	</div>

    <!-- Scripts -->
    <?php echo $this->inlineScript()
        ->prependFile($this->basePath('js/custom.js'))
        ->prependFile($this->basePath('bower_components/bootstrap/dist/js/bootstrap.min.js'))
        ->prependFile($this->basePath('bower_components/jquery/dist/jquery.min.js'));
    ?>

  </body>
</html>