<?php
$form = $this->form;
?>
<div class="container">
	<div class="some-margin"></div>
	<h1 class="text-center proj-head">Simple Chat Test Project</h1>
	<div class="some-margin"></div>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
            <div id="resp-msg" class="alert alert-dismissable hidden">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                <div class="msg">
                </div>
            </div>
			<?php echo $this->form()->openTag($form); ?>
				<div class="form-group">
					<div class="col-md-10">
						<?php echo $this->formElement($form->get('message')); ?>
					</div>
				</div>
                <?php echo $this->formElement($form->get('submit')->setAttribute('class', 'btn btn-primary')); ?>
			<?php echo $this->form()->closeTag($form); ?>
		</div>
	</div>
	<div class="some-margin"></div>
	<div class="row">
        <img id="loading" class="margin_auto" src="<?php echo $this->basePath('images/preloader.gif'); ?>" style="display:none;"/>
		<table class="table table-bordered table-striped">
			<thead>
				<tr>
					<th class="col-md-4">Created</th>
					<th class="col-md-8">Text</th>
				</tr>
			</thead>
			<tbody id="result">
			</tbody>
		</table>
	</div>
</div>